# NumPy Exercise: Correlated Gaussian Random Variables

In many situations, we need to have a series of correlated Gaussian random variables, which can then be transformed into other distributions of interest (uniform, lognormal, etc.). Let's see how to do that with NumPy in Python.

### Given:  

|Variable | Value | Description |
| ---: | :---: | :--- |
|`n_real` | `1E6` | number of realizations|
|`n_vars` | 3 | number of variables to correlate|
|`cov` | `[[ 1. ,  0.2,  0.4], [ 0.2,  0.8,  0.3], [ 0.4,  0.3,  1.1]]` | covariance matrix|

### Theory

The procedure for generating correlated Gaussian is as follows:  
1. Sample `[n_vars x n_real]` (uncorrelated) normal random variables
2. Calculate `chol_mat`, the Cholesky decomposition of the covariance matrix
3. Matrix-multiply your random variables with `chol_mat` to produce a `[n_vars x n_real]` array of correlated Gaussian variables

### Exercise

Do the following:  
1. Fill in the blank cells below so that the code follows the theory outlined above.
2. Calculate the variances of the three samples of random variables. Does it match the diagonal of the covariance matrix?
3. Calculate the correlation coefficient between the first and second random samples. Does it match `cov[0, 1]`?

### Hints

- In the arrays of random variables, each row `i` corresponds to a *sample* of random variable `i` (just FYI).
- Google is your friend :)

In [4]:
  # import any needed modules here
import numpy as np

In [7]:
n_real = int(1e6)  # number of realizations
n_vars =  3 # number of random variables we want to correlate
cov = [[ 1. ,  0.2,  0.4], [ 0.2,  0.8,  0.3], [ 0.4,  0.3,  1.1]] # covariance matrix

In [8]:
# create [n_vars x n_real] array of uncorrelated (unc) normal random variables
unc_vars = np.random.randn(n_vars, n_real)
unc_vars

array([[-0.42793298, -1.57143623, -0.27467896, ..., -1.72291516,
         0.65946078,  0.94224101],
       [ 0.16876072,  0.29700096, -1.1379556 , ...,  0.51925511,
        -1.73066367, -0.0873705 ],
       [-0.36424998,  1.82434757, -1.27681409, ..., -2.08753963,
         0.64646578,  0.0599019 ]])

In [9]:
# calculate the cholesky decomposition of the covariance matrix
chol_mat = np.linalg.cholesky(cov)
chol_mat

array([[1.        , 0.        , 0.        ],
       [0.2       , 0.87177979, 0.        ],
       [0.4       , 0.25235731, 0.9361174 ]])

In [10]:
# [n_vars x n_real] array of correlated (cor) random variables
cor_vars = np.dot(chol_mat, unc_vars)
cor_vars

array([[-0.42793298, -1.57143623, -0.27467896, ..., -1.72291516,
         0.65946078,  0.94224101],
       [ 0.06153559, -0.05536781, -1.04698249, ...,  0.10809307,
        -1.37686545,  0.11228037],
       [-0.46956594,  1.15417938, -1.59229088, ..., -2.51231041,
         0.43220656,  0.41092304]])

In [11]:
  # calculate variances of each sample of random variables
variances = np.var(cor_vars, axis=1)
variances

array([1.00158583, 0.79905924, 1.09941059])

In [12]:
  # calculate the correlation coefficient between the first and second random samples
correlation = np.corrcoef(cor_vars[0], cor_vars[1])[0, 1]
correlation

0.22405438321282958

In [14]:
# Print output
print("Variances:", variances)
print("Diagonal of covariance:", np.diag(cov))

Variances: [1.00158583 0.79905924 1.09941059]
Diagonal of covariance: [1.  0.8 1.1]
